[package]
name = "ef-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
serde = { version = '1.0', default-features = false, features = ['derive'] }
serde_json = { version = '1.0' }
clap = "2.33"
sha2 = "0.10.6"
hex = "0.4.3"
redis = "0.26.1"
log = "0.4.22"
